# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c5894abc0aa1c78cb611dca9c4b77d7809a779af30c3e908e3008fc7a5decddf1bee21fbc0d9576dd943a3427f2beae33c7bca07c882556a4c2dabb5b14019d

test:
  secret_key_base: a8bd23eb4dae417bb083c8ebdab5faae2eea410dc91a047855910118625e7e15f81e936b7f6ebf3f791997bf2d36a692b55db929142c0bf05db0789dbab60f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
